# Generated by Django 4.2.7 on 2023-12-14 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lettings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="address",
            table=None,
        ),
        migrations.AlterModelTable(
            name="letting",
            table=None,
        ),
    ]
