name: Render deploy
on:
  workflow_run:
    workflows: [ "Containerize" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/master' }}

    steps:
      - name: Deploy to production
        uses: sws2apps/render-deployment@v1.6.0
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
