name: Render deploy
on:
  workflow_run:
    workflows: [ "Containerize" ]
    types:
      - completed
#  push:
#    branches: [ develop ]
#  pull_request:
#    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: bounceapp/render-action@0.6.0
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          render-token: ${{ secrets.RENDER_API_KEY }}
#          wait-for-success: true
