name: Render deploy
on:
  workflow_run:
    workflows: [ "Containerize" ]
    types:
      - completed
#  push:
#    branches: [ develop ]
#  pull_request:
#    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: sws2apps/render-deployment@v1.6.0
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
#          wait-for-success: true
